version: '3.8'

services:
  authservice:
    build:
      context: ./AuthService
      dockerfile: src/AuthService.Web/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO__CONNECTION_STRING=mongodb+srv://<user>:<password>@<cluster>.mongodb.net/<dbname>?retryWrites=true&w=majoritmongodb+srv://luis019dell:U3TMdejvVgx7Ju6U@cluster0.epql6ez.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO__DATABASE=mototaxi
    depends_on: []
volumes:
  mongo_data:
