version: '3.8'

services:

  authservice:
    build:
      context: ./AuthService
      dockerfile: src/AuthService.Web/Dockerfile
    ports:
      - "5000:5000"

  websocketservice:
    build:
      context: ./MicroServicio.WebSocketReservacion/
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  tarifasservice:
    build:
      context: ./MicroServicio.Tarifas
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  conductoreservice:
    build:
      context: ./MicroServicio.Conductores
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

  reservacionesservice:
    build:
      context: ./MicroServicio.Reservaciones
      dockerfile: Dockerfile
    ports:
      - "5004:5004"

  codigoverificacionservice:
    build:
      context: ./MicroServicio.CodigoVerificacion
      dockerfile: Dockerfile
    ports:
      - "5005:5005"

  validarverificacionservice:
    build:
      context: ./MicroServicio.ValidarCodigoVerificacion
      dockerfile: Dockerfile
    ports:
      - "5006:5006"

networks:
  micro_net:
    driver: bridge
