services:
  authservice:
    build:
      context: ./AuthService
      dockerfile: src/AuthService.Web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MONGO__CONNECTION_STRING=mongodb+srv://<user>:<password>@<cluster>.mongodb.net/<dbname>?retryWrites=true&w=majority
      - MONGO__DATABASE=mototaxi

  tarifaservice:
    build:
      context: ./MicroServicio.Tarifas
      dockerfile: Dockerfile

  conductoresservice:
    build:
      context: ./MicroServicio.Conductores
      dockerfile: Dockerfile

  reservasservice:
    build:
      context: ./MicroServicio.Reservaciones
      dockerfile: Dockerfile

  codigoverificacionservice:
    build:
      context: ./MicroServicio.CodigoVerificacion
      dockerfile: Dockerfile
