events {}

http {
    server {
        listen 80;
        server_name auth.mototaxi.com tarifas.mototaxi.com conductores.mototaxi.com reservas.mototaxi.com codigoverificacion.mototaxi.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        
        server_name auth.mototaxi.com;
        ssl_certificate /etc/letsencrypt/live/auth.mototaxi.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/auth.mototaxi.com/privkey.pem;

        location / {
            proxy_pass http://authservice:8080;
        }
    }

    server {
        listen 443 ssl;
        
        server_name tarifas.mototaxi.com;
        ssl_certificate /etc/letsencrypt/live/tarifas.mototaxi.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/tarifas.mototaxi.com/privkey.pem;

        location / {
            proxy_pass http://tarifaservice:8080;
        }
    }

    server {
        listen 443 ssl;
        
        server_name conductores.mototaxi.com;
        ssl_certificate /etc/letsencrypt/live/conductores.mototaxi.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/conductores.mototaxi.com/privkey.pem;

        location / {
            proxy_pass http://conductoresservice:8080;
        }
    }

    server {
        listen 443 ssl;
        
        server_name reservas.mototaxi.com;
        ssl_certificate /etc/letsencrypt/live/reservas.mototaxi.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/reservas.mototaxi.com/privkey.pem;

        location / {
            proxy_pass http://reservasservice:8080;
        }
    }

    server {
        listen 443 ssl;
        
        server_name codigoverificacion.mototaxi.com;
        ssl_certificate /etc/letsencrypt/live/codigoverificacion.mototaxi.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/codigoverificacion.mototaxi.com/privkey.pem;

        location / {
            proxy_pass http://codigoverificacionservice:8080;
        }
    }
}
