# Usa la imagen base de .NET
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
//Corregis este dockerFile
RUN dotnet restore "src/AuthService.Web/AuthService.Web.csproj"
RUN dotnet publish "src/AuthService.Web/AuthService.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "AuthService.Web.dll"]
