# LocationService
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ./src/LocationService.Web/LocationService.Web.csproj .
RUN dotnet restore LocationService.Web.csproj

COPY ./src/LocationService.Web .
RUN dotnet publish LocationService.Web.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "LocationService.Web.dll"]
