// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServicioTarifas.Infrastructure.Data;

#nullable disable

namespace ServicioTarifas.Infrastructure.Migrations
{
    [DbContext(typeof(TarifasDbContext))]
    [Migration("20251125050314_ModifyDatabase")]
    partial class ModifyDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServicioTarifas.Domain.Models.CustomFare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("ApplicableDays")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("FareId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FareId");

                    b.ToTable("CustomFares");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.Fare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceMax")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceMin")
                        .HasColumnType("double precision");

                    b.Property<int>("FareType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Fares");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.FarePaymentMethod", b =>
                {
                    b.Property<Guid>("FareId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.HasKey("FareId", "PaymentMethodId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("FarePaymentMethods");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.GlobalFare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FareId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FareId");

                    b.ToTable("GlobalFares");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.PrivateFare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FareId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FareId");

                    b.ToTable("PrivateFares");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.StopFare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FareId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxStopsAllowed")
                        .HasColumnType("integer");

                    b.Property<double>("PricePerStop")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FareId");

                    b.ToTable("StopFares");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.CustomFare", b =>
                {
                    b.HasOne("ServicioTarifas.Domain.Models.Fare", "Fare")
                        .WithMany("CustomFares")
                        .HasForeignKey("FareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.FarePaymentMethod", b =>
                {
                    b.HasOne("ServicioTarifas.Domain.Models.Fare", "Fare")
                        .WithMany("FarePaymentMethods")
                        .HasForeignKey("FareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicioTarifas.Domain.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("FarePaymentMethods")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fare");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.GlobalFare", b =>
                {
                    b.HasOne("ServicioTarifas.Domain.Models.Fare", "Fare")
                        .WithMany("GlobalFares")
                        .HasForeignKey("FareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.PrivateFare", b =>
                {
                    b.HasOne("ServicioTarifas.Domain.Models.Fare", "Fare")
                        .WithMany("PrivateFares")
                        .HasForeignKey("FareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.StopFare", b =>
                {
                    b.HasOne("ServicioTarifas.Domain.Models.Fare", "Fare")
                        .WithMany("StopFares")
                        .HasForeignKey("FareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.Fare", b =>
                {
                    b.Navigation("CustomFares");

                    b.Navigation("FarePaymentMethods");

                    b.Navigation("GlobalFares");

                    b.Navigation("PrivateFares");

                    b.Navigation("StopFares");
                });

            modelBuilder.Entity("ServicioTarifas.Domain.Models.PaymentMethod", b =>
                {
                    b.Navigation("FarePaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
